const express = require('express');
const router = express.Router();

const Home = require('../controllers/home');
const user = require('../controllers/user');
const err404 = require('../controllers/404');
const ativos = require('../controllers/ativos');
const local = require('../controllers/local');
const so = require('../controllers/so');
const placaMae = require('../controllers/placamae');

router.get('/', Home.index);
router.get('/usuario/cadastro', user.indexCardUser);
router.get('/usuario', user.indexUser);
router.get('/usuario', user.dataUser);
router.get('/usuario/editar/:id', user.show);
router.delete('/usuario/deletar/:id', user.deletar);
router.put('/usuario/editar/:id', user.update);
router.post('/usuario/cadastro', user.add);
router.get('/ativos', ativos.indexAtivos);
router.get('/ativos/local', ativos.local);
router.get('/ativos/so', ativos.so);
router.get('/ativos/placaMae', ativos.placa);
router.get('/local', local.index);
router.get('/placaMae', placaMae.index);
router.get('/placaMae/cadastro', placaMae.indexCadastro);
router.post('/placaMae/cadastro', placaMae.add);
router.get('/placaMae/editar/:id', placaMae.show);
router.put('/placaMae/editar/:id', placaMae.update);
router.delete('/placaMae/deletar/:id', placaMae.deletar);
router.get('/so', so.index);
router.get('/so/cadastro', so.indexCadastro);
router.post('/so/cadastro', so.add);
router.put('/so/editar/:id', so.update);
router.delete('/so/deletar/:id', so.deletar);
router.get('/local/cadastro', local.indexCadastro);
router.post('/local/cadastro', local.add);
router.get('/local/editar/:id', local.show);
router.put('/local/editar/:id', local.update);
router.delete('/local/deletar/:id', local.deletar);
router.get('*', err404.index);

module.exports = router;
