const express = require('express');
const router = express.Router();

const Home = require('../controllers/home');
const user = require('../controllers/user');
const err404 = require('../controllers/404');
const ativos = require('../controllers/ativos');
const local = require('../controllers/local');
const so = require('../controllers/so');
const placaMae = require('../controllers/placamae');
const processador = require('../controllers/processador');
const memoria = require('../controllers/memoria');
const armazenamento = require('../controllers/armazenamento');
const fonte = require('../controllers/fonte');
const placas = require('../controllers/placas');
const gabinete = require('../controllers/gabinete');
const monitor = require('../controllers/monitor');
const cooler = require('../controllers/cooler');

router.get('/', Home.index);
router.get('/usuario/cadastro', user.indexCardUser);
router.get('/usuario', user.indexUser);
router.get('/usuario', user.dataUser);
router.get('/usuario/editar/:id', user.show);
router.delete('/usuario/deletar/:id', user.deletar);
router.put('/usuario/editar/:id', user.update);
router.post('/usuario/cadastro', user.add);
router.get('/ativos', ativos.indexAtivos);
router.get('/ativos/local', ativos.local);
router.get('/ativos/so', ativos.so);
router.get('/ativos/placaMae', ativos.placa);
router.get('/ativos/processador', ativos.processadores);
router.get('/ativos/memoria', ativos.memoria);
router.get('/ativos/armazenamento', ativos.armazenamentos);
router.get('/ativos/fonte', ativos.fontes);
router.get('/ativos/placaVideo', ativos.placaVideo);
router.get('/ativos/monitor', ativos.monitors);
router.get('/ativos/gabinete', ativos.gabinetes);
router.get('/ativos/cooler', ativos.coolers);

router.get('/local', local.index);
router.get('/placaMae', placaMae.index);
router.get('/placaMae/cadastro', placaMae.indexCadastro);
router.post('/placaMae/cadastro', placaMae.add);
router.get('/placaMae/editar/:id', placaMae.show);
router.put('/placaMae/editar/:id', placaMae.update);
router.delete('/placaMae/deletar/:id', placaMae.deletar);
router.get('/processador', processador.index);
router.get('/processador/cadastro', processador.indexCadastro);
router.post('/processador/cadastro', processador.add);
router.get('/processador/editar/:id', processador.show);
router.put('/processador/editar/:id', processador.update);
router.delete('/processador/deletar/:id', processador.deletar);
router.get('/memoriaRam', memoria.index);
router.get('/memoriaRam/cadastro', memoria.indexCadastro);
router.post('/memoriaRam/cadastro', memoria.add);
router.get('/memoriaRam/editar/:id', memoria.show);
router.put('/memoriaRam/editar/:id', memoria.update);
router.delete('/memoriaRam/deletar/:id', memoria.deletar);
router.get('/armazenamento', armazenamento.index);
router.get('/armazenamento/cadastro', armazenamento.indexCadastro);
router.post('/armazenamento/cadastro', armazenamento.add);
router.get('/armazenamento/editar/:id', armazenamento.show);
router.put('/armazenamento/editar/:id', armazenamento.update);
router.delete('/armazenamento/deletar/:id', armazenamento.deletar);
router.get('/placaVideo', placas.index);
router.get('/placaVideo/cadastro', placas.indexCadastro);
router.post('/placaVideo/cadastro', placas.add);
router.get('/placaVideo/editar/:id', placas.show);
router.put('/placaVideo/editar/:id', placas.update);
router.delete('/placaVideo/deletar/:id', placas.deletar);
router.get('/fonte', fonte.index);
router.get('/fonte/cadastro', fonte.indexCadastro);
router.post('/fonte/cadastro', fonte.add);
router.get('/fonte/editar/:id', fonte.show);
router.put('/fonte/editar/:id', fonte.update);
router.delete('/fonte/deletar/:id', fonte.deletar);
router.get('/gabinete', gabinete.index);
router.get('/gabinete/cadastro', gabinete.indexCadastro);
router.post('/gabinete/cadastro', gabinete.add);
router.get('/gabinete/editar/:id', gabinete.show);
router.put('/gabinete/editar/:id', gabinete.update);
router.delete('/gabinete/deletar/:id', gabinete.deletar);
router.get('/monitor', monitor.index);
router.get('/monitor/cadastro', monitor.indexCadastro);
router.post('/monitor/cadastro', monitor.add);
router.get('/monitor/editar/:id', monitor.show);
router.put('/monitor/editar/:id', monitor.update);
router.delete('/monitor/deletar/:id', monitor.deletar);
router.get('/cooler', cooler.index);
router.get('/cooler/cadastro', cooler.indexCadastro);
router.post('/cooler/cadastro', cooler.add);
router.get('/cooler/editar/:id', cooler.show);
router.put('/cooler/editar/:id', cooler.update);
router.delete('/cooler/deletar/:id', cooler.deletar);
router.get('/so', so.index);
router.get('/so/cadastro', so.indexCadastro);
router.post('/so/cadastro', so.add);
router.put('/so/editar/:id', so.update);
router.delete('/so/deletar/:id', so.deletar);
router.get('/local/cadastro', local.indexCadastro);
router.post('/local/cadastro', local.add);
router.get('/local/editar/:id', local.show);
router.put('/local/editar/:id', local.update);
router.delete('/local/deletar/:id', local.deletar);
router.get('*', err404.index);

module.exports = router;
